execute:
  freeze: auto
project:
  resources:
    - "Resources"
    - "style_site.scss"
  type: website
  output-dir: public
website:
  title: "Simplified NeuROM"
  # pdf-engine: lualatex
  description: "A simplified 1D NeuROM demo"
  navbar:
    # left:
    #   - href: demos/1D_element_based_LBFGS.ipynb
    #     text: Simplified 1D NeuROM - L-BFGS
    #   - href: demos/1D_element_based.ipynb
    #     text: Simplified 1D NeuROM - Adam
    right:
      - text: "{{< iconify fa6-solid:rocket width=17 title=Binder >}}"
        href: https://mybinder.org/v2/gh/AlexandreDabySeesaram/simplified_1d_Neurom/main?urlpath=lab/tree/./demos/
      - icon: github
        href: https://github.com/AlexandreDabySeesaram/Simplified_NeuROM_demos
      - text: "{{< iconify fa6-solid:download width=17 title=dl >}}"
        href: https://github.com/AlexandreDabySeesaram/Simplified_NeuROM_demos/archive/refs/heads/master.zip
      - href: https://alexandredabyseesaram.github.io/
        text: Alexandre Daby-Seesaram's homepage

  sidebar:
    style: "floating"
    search: true
    contents:
      - text: "Home"
        href: index.qmd
      - section: "1D NeuROM"
        contents:
          - href: demos/1D_element_based_LBFGS.ipynb
            text: L-BFGS
          - href: demos/1D_element_based.ipynb
            text: Adam


format:
  # pdf: default
  html:
    code-fold: show
    theme:
      light: [flatly,style_site.scss]
      dark: [darkly,style_site_dark.scss]      
    css: styles.css
    toc: true
    html-math-method: mathjax



